### ISSUE TITLE
师兄你好

### ISSUE THREAD

**Issue by May-forever** [fupiao1998/RCF-keras#1]
尊敬的毛师兄，你好，打扰你了，我是一名南京航空航天大学的研究生，我最近拜读了你在github上上传的一系列RCF的代码：https://github.com/fupiao1998/RCF-keras，我对师兄的工作深表钦佩。

我最近也在从事关于边缘检测方面的研究，也发了邮件给师兄，可是被拒收了。关于师兄上传的代码，还有些地方不明白，我想冒昧的咨询一下师兄，可不可以发你的微信号给我，方便以后和你多学习多交流。

期待你的回信，先谢谢师兄了。

**Comment by MaoYuxin25** [comment]
不好意思刚看到，我的qq是764465829，你可以加我的QQ联系
